# Generated by Django 3.1.5 on 2021-01-18 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(auto_now=True)),
                ('mountain_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('caption', models.CharField(blank=True, max_length=280, null=True)),
                ('mountain', models.CharField(choices=[('Washington', 'washington'), ('Adams', 'adams'), ('Jefferson', 'jefferson'), ('Monroe', 'monroe'), ('Madison', 'madison'), ('Lafayette', 'lafayette'), ('Lincoln', 'lincoln'), ('South Twin', 'south twin'), ('Carter Dome', 'carter dome'), ('Moosilauke', 'moosilauke'), ('Eisenhower', 'eisenhower'), ('North Twin', 'north twin'), ('Carrigain', 'carrigain'), ('Bond', 'bond'), ('Middle Carter', 'middle carter'), ('West Bond', 'west bond'), ('Garfield', 'garfield'), ('Liberty', 'liberty'), ('South Carter', 'south carter'), ('Wildcat', 'wildcat'), ('Hancock', 'hancock'), ('South Kinsman', 'south kinsman'), ('Field', 'field'), ('Osceola', 'osceola'), ('Flume', 'flume'), ('South Hancock', 'south hancock'), ('Pierce', 'pierce'), ('North Kinsman', 'north kinsman'), ('Willey', 'willey'), ('Bondcliff', 'bondcliff'), ('Zealand', 'zealand'), ('North Tripyramid', 'north tripyramid'), ('Cabot', 'cabot'), ('East Osceola', 'east osceola'), ('Middle Tripyramid', 'middle tripyramid'), ('Cannon', 'cannon'), ('Wildcat D', 'wildcat d'), ('Hale', 'hale'), ('Jackson', 'jackson'), ('Tom', 'tom'), ('Moriah', 'moriah'), ('Passaconaway', 'passaconaway'), ("Owl's Head", 'owls head'), ('Galehead', 'galehead'), ('Whiteface', 'whiteface'), ('Waumbek', 'waumbek'), ('Isolation', 'isolation'), ('Tecumseh', 'tecumseh')], max_length=25)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
