# Generated by Django 3.1.5 on 2021-01-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nh48_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mountain',
            field=models.CharField(choices=[('washington', 'Washington'), ('adams', 'Adams'), ('jefferson', 'Jefferson'), ('monroe', 'Monroe'), ('madison', 'Madison'), ('lafayette', 'Lafayette'), ('lincoln', 'Lincoln'), ('south twin', 'South Twin'), ('carter dome', 'Carter Dome'), ('moosilauke', 'Moosilauke'), ('eisenhower', 'Eisenhower'), ('north twin', 'North Twin'), ('carrigain', 'Carrigain'), ('bond', 'Bond'), ('middle carter', 'Middle Carter'), ('west bond', 'West Bond'), ('garfield', 'Garfield'), ('liberty', 'Liberty'), ('south carter', 'South Carter'), ('wildcat', 'Wildcat'), ('hancock', 'Hancock'), ('south kinsman', 'South Kinsman'), ('field', 'Field'), ('osceola', 'Osceola'), ('flume', 'Flume'), ('south hancock', 'South Hancock'), ('pierce', 'Pierce'), ('north kinsman', 'North Kinsman'), ('willey', 'Willey'), ('bondcliff', 'Bondcliff'), ('zealand', 'Zealand'), ('north tripyramid', 'North Tripyramid'), ('cabot', 'Cabot'), ('east osceola', 'East Osceola'), ('middle tripyramid', 'Middle Tripyramid'), ('cannon', 'Cannon'), ('wildcat d', 'Wildcat D'), ('hale', 'Hale'), ('jackson', 'Jackson'), ('tom', 'Tom'), ('moriah', 'Moriah'), ('passaconaway', 'Passaconaway'), ('owls head', "Owl's Head"), ('galehead', 'Galehead'), ('whiteface', 'Whiteface'), ('waumbek', 'Waumbek'), ('isolation', 'Isolation'), ('tecumseh', 'Tecumseh')], max_length=25),
        ),
    ]
